### ISSUE TITLE
小程序无法添加header

### ISSUE THREAD

**Issue by rzrobert** [10cella/weapp.socket.io#16]
const sendHeader = {
    "pt": "weixin",
    "sv": "18",
    "lg": "zh-CN"
  };
  onSocket = io.connect(server, {
    path: "/" + path, 
    transports: ['polling'],
    transportOptions: {
      polling: {
        extraHeaders: sendHeader
      }
    }
  });

**Comment by ccckblaze** [comment]
same issues @

**Comment by gongzili456** [comment]
@rzrobert weapp.socket.io not support polling transport

**Comment by gongzili456** [comment]
@rzrobert @ccckblaze 关于 header 的使用，[socket.io 官方文档](https://socket.io/docs/client-api/#With-extraHeaders)有给出解释, 在 websokcet transport 模式下无法自定义 header


> With extraHeaders
This only works if polling transport is enabled (which is the default). Custom headers will not be appended when using websocket as the transport. This happens because the WebSocket handshake does not honor custom headers. (For background see the WebSocket protocol RFC)
